### ISSUE TITLE
Pin pyyaml at 5.4.1

### ISSUE THREAD

**Issue by mjw99** [conda-forge/yank-feedstock#1]
With pyyaml 6.0,  yank analyze fails:

```

(openmm) mjw@ubu:~/workspace/yank-examples/examples/hydration/phenol/explicit_1$ yank analyze --store=experiments
Traceback (most recent call last):
  File "/home/mjw/miniconda3/envs/openmm/bin/yank", line 10, in <module>
    sys.exit(main())
  File "/home/mjw/miniconda3/envs/openmm/lib/python3.9/site-packages/yank/cli.py", line 73, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/home/mjw/miniconda3/envs/openmm/lib/python3.9/site-packages/yank/commands/analyze.py", line 148, in dispatch
    single_run()
  File "/home/mjw/miniconda3/envs/openmm/lib/python3.9/site-packages/mpiplus/mpiplus.py", line 271, in _wrapper
    return run_single_node(rank, task, *args, **kwargs)
  File "/home/mjw/miniconda3/envs/openmm/lib/python3.9/site-packages/mpiplus/mpiplus.py", line 220, in run_single_node
    result = task(*args, **kwargs)
  File "/home/mjw/miniconda3/envs/openmm/lib/python3.9/site-packages/yank/commands/analyze.py", line 143, in single_run
    output = analyze.analyze_directory(args['--store'], **analyzer_kwargs)
  File "/home/mjw/miniconda3/envs/openmm/lib/python3.9/site-packages/yank/analyze.py", line 782, in analyze_directory
    auto_experiment_analyzer = ExperimentAnalyzer(source_directory, **analyzer_kwargs)
  File "/home/mjw/miniconda3/envs/openmm/lib/python3.9/site-packages/yank/analyze.py", line 299, in __init__
    analysis = yaml.load(f)
TypeError: load() missing 1 required positional argument: 'Loader'
Exception ignored in: <function ExperimentAnalyzer.__del__ at 0x7f8bdf6b5d30>
Traceback (most recent call last):
  File "/home/mjw/miniconda3/envs/openmm/lib/python3.9/site-packages/yank/analyze.py", line 336, in __del__
    for phase, analyzer in self.analyzers.items():
AttributeError: 'ExperimentAnalyzer' object has no attribute 'analyzers'
```
See also:
https://github.com/yaml/pyyaml/issues/576

**Comment by jchodera** [comment]
This one may be much more difficult to address if the pyyaml API changed, so I suggest we should indeed pin `pyyaml <6` for now.

**Comment by jaimergp** [comment]
You might want a repodata patch too.

https://github.com/conda-forge/conda-forge-repodata-patches-feedstock

**Comment by mjw99** [comment]
Is there anything I can do to help with this? I see another issue cropping up with ref to this https://github.com/choderalab/yank/issues/1264 

Alternatively, it may only require the loader in analyze.py instance, as mentioned in https://github.com/choderalab/yank/issues/1152 , to be fixed.

**Comment by jchodera** [comment]
@mikemhenry: Can you look into this when you get a chance?
